# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30cb3a02395783de9f973455c9c774a882abd1d96e57d098e3a89133ba44e22bf0c078dd68436cc38549828939449bcd730da4b3fb3af7654cc5f804f34740ed

test:
  secret_key_base: b36c7154cdf3a3cf4b33a6cc685833f2a52dea45459361c2fe9844ffd024b924278c757241f49d273bef0a8b561b76d0a35058e783f6ddc552f08663a9d196dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
